name: build
'on':
  - pull_request
  - push
jobs:
  build:
    strategy:
      matrix:
        java:
          - 16
        os:
          - ubuntu-20.04
          - windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: 'setup jdk ${{ matrix.java }}'
        uses: actions/setup-java@v1
        with:
          java-version: '${{ matrix.java }}'
      - name: make gradle wrapper executable
        if: '${{ runner.os != ''Windows'' }}'
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: '${{ runner.os == ''Linux'' && matrix.java == ''16'' }}'
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
